/**
 * Golden file parity tests — verify TypeScript reads Go-generated shards exactly.
 *
 * Golden files are generated by the Go reference implementation at:
 *   testdata/generate_golden.go
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect, beforeAll } from 'vitest';

import {
  ShardReader,
  computeCrc32c,
  computeXxhash64,
  initXxhash,
} from '../index.js';

// Resolve testdata relative to this source file using import.meta.url
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const TESTDATA = resolve(__dirname, '../../../testdata');
const MANIFEST_PATH = resolve(TESTDATA, 'golden_manifest.json');

// ============================================================
// Types matching the manifest JSON
// ============================================================

interface ManifestEntry {
  name: string;
  name_hash: number;
  content_type: number;
  orig_size: number;
  disk_size: number;
  checksum: number;
  compressed: boolean;
  data_sha256: string;
}

interface ManifestFile {
  filename: string;
  sha256: string;
  header: {
    version: number;
    role: number;
    flags: number;
    alignment: number;
    compression_default: number;
    entry_count: number;
    index_entry_size: number;
    string_table_offset: number;
    data_section_offset: number;
    schema_offset: number;
    total_file_size: number;
  };
  entries: ManifestEntry[];
}

interface Manifest {
  files: ManifestFile[];
}

// ============================================================
// Helpers
// ============================================================

function sha256hex(data: Buffer): string {
  return createHash('sha256').update(data).digest('hex');
}

function loadGolden(filename: string): Buffer {
  return readFileSync(resolve(TESTDATA, filename));
}

// File index labels matching the Python tests
const FILE_LABELS = ['basic', 'types', 'align16', 'noalign', 'wshard', 'hierarchical'];

// ============================================================
// Setup
// ============================================================

let manifest: Manifest;

beforeAll(async () => {
  await initXxhash();
  manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as Manifest;
});

// ============================================================
// Basic existence tests
// ============================================================

describe('golden manifest', () => {
  it('manifest file exists', () => {
    const buf = readFileSync(MANIFEST_PATH);
    expect(buf.length).toBeGreaterThan(0);
  });

  it('all 6 golden files exist', () => {
    for (const gf of manifest.files) {
      const buf = loadGolden(gf.filename);
      expect(buf.length, `${gf.filename} should be non-empty`).toBeGreaterThan(0);
    }
  });
});

// ============================================================
// Per-file SHA256 check
// ============================================================

describe('file SHA256', () => {
  for (let i = 0; i < 6; i++) {
    const label = FILE_LABELS[i];
    it(`${label}: SHA256 matches manifest`, () => {
      const gf = manifest.files[i];
      const data = loadGolden(gf.filename);
      const actual = sha256hex(data);
      expect(actual).toBe(gf.sha256);
    });
  }
});

// ============================================================
// Header fields
// ============================================================

describe('header fields', () => {
  for (let i = 0; i < 6; i++) {
    const label = FILE_LABELS[i];
    it(`${label}: all header fields match`, () => {
      const gf = manifest.files[i];
      const buf = loadGolden(gf.filename);
      const reader = new ShardReader(buf);
      const h = reader.header();
      const gh = gf.header;

      expect(h.version).toBe(gh.version);
      expect(h.role).toBe(gh.role);
      expect(h.flags).toBe(gh.flags);
      expect(h.alignment).toBe(gh.alignment);
      expect(h.compressionDefault).toBe(gh.compression_default);
      expect(h.entryCount).toBe(gh.entry_count);
      expect(h.indexEntrySize).toBe(gh.index_entry_size);
      expect(h.stringTableOffset).toBe(BigInt(gh.string_table_offset));
      expect(h.dataSectionOffset).toBe(BigInt(gh.data_section_offset));
      expect(h.schemaOffset).toBe(BigInt(gh.schema_offset));
      expect(h.totalFileSize).toBe(BigInt(gh.total_file_size));
    });
  }
});

// ============================================================
// Entry count
// ============================================================

describe('entry count', () => {
  for (let i = 0; i < 6; i++) {
    const label = FILE_LABELS[i];
    it(`${label}: entry count matches`, () => {
      const gf = manifest.files[i];
      const reader = new ShardReader(loadGolden(gf.filename));
      expect(reader.entryCount()).toBe(gf.entries.length);
    });
  }
});

// ============================================================
// Entry names
// ============================================================

describe('entry names', () => {
  for (let i = 0; i < 6; i++) {
    const label = FILE_LABELS[i];
    it(`${label}: entry names match`, () => {
      const gf = manifest.files[i];
      const reader = new ShardReader(loadGolden(gf.filename));
      const expected = gf.entries.map(e => e.name);
      expect(reader.entryNames()).toEqual(expected);
    });
  }
});

// ============================================================
// Entry details
// ============================================================

describe('entry details', () => {
  for (let i = 0; i < 6; i++) {
    const label = FILE_LABELS[i];
    it(`${label}: entry details match`, () => {
      const gf = manifest.files[i];
      const reader = new ShardReader(loadGolden(gf.filename));

      for (let j = 0; j < gf.entries.length; j++) {
        const ge = gf.entries[j];
        const info = reader.getEntryInfo(j);

        expect(info.name, `entry ${j} name`).toBe(ge.name);
        // JSON parses large uint64 name_hash values with floating-point precision loss.
        // Re-compute the expected hash from the entry name instead.
        const expectedHash = computeXxhash64(ge.name);
        expect(info.nameHash, `entry ${j} name_hash`).toBe(expectedHash);
        expect(info.contentType, `entry ${j} content_type`).toBe(ge.content_type);
        expect(Number(info.origSize), `entry ${j} orig_size`).toBe(ge.orig_size);
        expect(Number(info.diskSize), `entry ${j} disk_size`).toBe(ge.disk_size);
        expect(info.checksum, `entry ${j} checksum`).toBe(ge.checksum);
        expect(info.compressed, `entry ${j} compressed`).toBe(ge.compressed);
      }
    });
  }
});

// ============================================================
// Entry data SHA256
// ============================================================

describe('entry data SHA256', () => {
  for (let i = 0; i < 6; i++) {
    const label = FILE_LABELS[i];
    it(`${label}: entry data SHA256 matches`, () => {
      const gf = manifest.files[i];
      const reader = new ShardReader(loadGolden(gf.filename));

      for (let j = 0; j < gf.entries.length; j++) {
        const ge = gf.entries[j];
        const data = reader.readEntry(j);
        const actual = sha256hex(data);
        expect(actual, `entry ${j} (${ge.name}) data SHA256`).toBe(ge.data_sha256);
      }
    });
  }
});

// ============================================================
// Lookup by name
// ============================================================

describe('lookup by name', () => {
  for (let i = 0; i < 6; i++) {
    const label = FILE_LABELS[i];
    it(`${label}: lookup returns correct index`, () => {
      const gf = manifest.files[i];
      const reader = new ShardReader(loadGolden(gf.filename));

      for (let j = 0; j < gf.entries.length; j++) {
        const ge = gf.entries[j];
        expect(reader.lookup(ge.name), `lookup(${ge.name})`).toBe(j);
        expect(reader.hasEntry(ge.name), `hasEntry(${ge.name})`).toBe(true);
      }

      expect(reader.lookup('nonexistent')).toBe(-1);
      expect(reader.hasEntry('nonexistent')).toBe(false);
    });
  }
});

// ============================================================
// Read by name
// ============================================================

describe('read by name', () => {
  for (let i = 0; i < 6; i++) {
    const label = FILE_LABELS[i];
    it(`${label}: readEntryByName returns correct data`, () => {
      const gf = manifest.files[i];
      const reader = new ShardReader(loadGolden(gf.filename));

      for (const ge of gf.entries) {
        const data = reader.readEntryByName(ge.name);
        expect(sha256hex(data), `data SHA256 for ${ge.name}`).toBe(ge.data_sha256);
      }
    });
  }
});

// ============================================================
// CRC32C known values
// ============================================================

describe('CRC32C', () => {
  it('hello world = 3381945770', () => {
    const result = computeCrc32c(Buffer.from('hello world'));
    expect(result).toBe(3381945770);
  });

  it('empty buffer = 0', () => {
    expect(computeCrc32c(Buffer.alloc(0))).toBe(0);
  });

  it('pattern 1k = 752840335', () => {
    const data = Buffer.from(Array.from({ length: 1024 }, (_, i) => i % 256));
    expect(computeCrc32c(data)).toBe(752840335);
  });
});

// ============================================================
// xxHash64 known values
// ============================================================

describe('xxHash64', () => {
  it('greeting = 16700977181434310015', () => {
    const result = computeXxhash64('greeting');
    // JSON can't represent this exactly as a number; use BigInt literal
    expect(result).toBe(16700977181434310015n);
  });

  it('pattern/1k = 11449517142474649281', () => {
    const result = computeXxhash64('pattern/1k');
    expect(result).toBe(11449517142474649281n);
  });

  it('metadata/model = 7724208215623586332', () => {
    const result = computeXxhash64('metadata/model');
    expect(result).toBe(7724208215623586332n);
  });
});

// ============================================================
// ListPrefix tests
// ============================================================

describe('listPrefix', () => {
  it('hierarchical: attention prefix returns 4 entries', () => {
    const gf = manifest.files[5]; // golden_hierarchical.shard
    const reader = new ShardReader(loadGolden(gf.filename));

    const attn = reader.listPrefix('layer.0/attention/');
    expect(attn.length).toBe(4);
    expect(attn.every(n => n.includes('attention'))).toBe(true);
  });

  it('hierarchical: ffn prefix returns 3 entries', () => {
    const gf = manifest.files[5];
    const reader = new ShardReader(loadGolden(gf.filename));

    const ffn = reader.listPrefix('layer.0/ffn/');
    expect(ffn.length).toBe(3);
    expect(ffn.every(n => n.includes('ffn'))).toBe(true);
  });

  it('wshard: signal/ prefix returns 1 entry', () => {
    const gf = manifest.files[4]; // golden_wshard.shard
    const reader = new ShardReader(loadGolden(gf.filename));

    const signals = reader.listPrefix('signal/');
    expect(signals.length).toBe(1);
  });

  it('wshard: omen/ prefix returns 1 entry', () => {
    const gf = manifest.files[4];
    const reader = new ShardReader(loadGolden(gf.filename));

    const omens = reader.listPrefix('omen/');
    expect(omens.length).toBe(1);
  });

  it('wshard: residual/ prefix returns 1 entry', () => {
    const gf = manifest.files[4];
    const reader = new ShardReader(loadGolden(gf.filename));

    const residuals = reader.listPrefix('residual/');
    expect(residuals.length).toBe(1);
  });
});
