/**
 * Cross-language safety tests — verify TypeScript reads Go-generated safety fixtures.
 *
 * Safety fixtures are generated by the Go reference implementation at:
 *   testdata/safety/
 *
 * Manifest: safety_manifest.json describes valid shards (with per-entry SHA256)
 * and corrupt shards (which must cause errors, never silently succeed).
 */

import { createHash } from 'node:crypto';
import { readFileSync, unlinkSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { describe, it, expect, beforeAll } from 'vitest';

import {
  ShardReader,
  ShardWriter,
  ShardStreamWriter,
  initXxhash,
  initCompression,
  ROLE_MOSH,
  ALIGN_64,
} from '../index.js';

// Resolve testdata relative to this source file using import.meta.url
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const SAFETY_DIR = resolve(__dirname, '../../../testdata/safety');
const MANIFEST_PATH = resolve(SAFETY_DIR, 'safety_manifest.json');

// ============================================================
// Types matching the safety manifest JSON
// ============================================================

interface SafetyManifestValidEntry {
  name: string;
  data_sha256: string;
  size: number;
}

interface SafetyManifestValidFile {
  filename: string;
  sha256: string;
  entry_count: number;
  entries: SafetyManifestValidEntry[];
}

interface SafetyManifestCorruptFile {
  filename: string;
  expected_error: string;
  description: string;
}

interface SafetyManifest {
  valid: SafetyManifestValidFile[];
  corrupt: SafetyManifestCorruptFile[];
}

// ============================================================
// Helpers
// ============================================================

function sha256hex(data: Buffer): string {
  return createHash('sha256').update(data).digest('hex');
}

function loadFixture(filename: string): Buffer {
  return readFileSync(resolve(SAFETY_DIR, filename));
}

// ============================================================
// Setup
// ============================================================

let manifest: SafetyManifest;

beforeAll(async () => {
  await initXxhash();
  await initCompression();
  manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as SafetyManifest;
});

// ============================================================
// Valid shard tests
// ============================================================

describe('safety: valid shards', () => {
  it('manifest lists valid files', () => {
    expect(manifest.valid.length).toBeGreaterThan(0);
  });

  describe.each([
    'valid_basic.shard',
    'valid_compressed.shard',
    'valid_empty_entry.shard',
    'valid_long_name.shard',
    'valid_unicode_name.shard',
    'valid_binary_data.shard',
  ])('%s', (filename) => {
    it('constructor succeeds', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      expect(mf, `${filename} not in manifest`).toBeDefined();
      const buf = loadFixture(filename);
      const reader = new ShardReader(buf);
      expect(reader).toBeDefined();
    });

    it('entry count matches manifest', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      const reader = new ShardReader(loadFixture(filename));
      expect(reader.entryCount()).toBe(mf.entry_count);
    });

    it('entry names match manifest', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      const reader = new ShardReader(loadFixture(filename));
      const expectedNames = mf.entries.map(e => e.name);
      expect(reader.entryNames()).toEqual(expectedNames);
    });

    it('entry data SHA256 matches manifest', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      const reader = new ShardReader(loadFixture(filename));

      for (let j = 0; j < mf.entries.length; j++) {
        const expected = mf.entries[j];
        const data = reader.readEntry(j);
        const actual = sha256hex(data);
        expect(actual, `entry ${j} (${expected.name}) SHA256`).toBe(expected.data_sha256);
      }
    });

    it('entry data sizes match manifest', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      const reader = new ShardReader(loadFixture(filename));

      for (let j = 0; j < mf.entries.length; j++) {
        const expected = mf.entries[j];
        const data = reader.readEntry(j);
        expect(data.length, `entry ${j} (${expected.name}) size`).toBe(expected.size);
      }
    });

    it('file SHA256 matches manifest', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      const buf = loadFixture(filename);
      expect(sha256hex(buf)).toBe(mf.sha256);
    });

    it('lookup by name works for all entries', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      const reader = new ShardReader(loadFixture(filename));

      for (let j = 0; j < mf.entries.length; j++) {
        const name = mf.entries[j].name;
        expect(reader.hasEntry(name), `hasEntry(${name})`).toBe(true);
        expect(reader.lookup(name), `lookup(${name})`).toBe(j);
      }
    });

    it('readEntryByName returns correct data', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      const reader = new ShardReader(loadFixture(filename));

      for (const entry of mf.entries) {
        const data = reader.readEntryByName(entry.name);
        expect(sha256hex(data), `readEntryByName(${entry.name}) SHA256`).toBe(entry.data_sha256);
      }
    });

    it('hasEntry returns true for all entries', () => {
      const mf = manifest.valid.find(v => v.filename === filename)!;
      const reader = new ShardReader(loadFixture(filename));

      for (const entry of mf.entries) {
        expect(reader.hasEntry(entry.name), `hasEntry(${entry.name})`).toBe(true);
      }
      expect(reader.hasEntry('__nonexistent__')).toBe(false);
    });

    it('lookup returns undefined/-1 for nonexistent names', () => {
      const reader = new ShardReader(loadFixture(filename));

      expect(reader.lookup('nonexistent')).toBe(-1);
      expect(reader.lookup('')).toBe(-1);
      expect(reader.lookup('__garbage__')).toBe(-1);
    });
  });
});

// ============================================================
// Corrupt shard tests
// ============================================================

describe('safety: corrupt shards', () => {
  it('manifest lists corrupt files', () => {
    expect(manifest.corrupt.length).toBeGreaterThan(0);
  });

  describe.each([
    'corrupt_bad_magic.shard',
    'corrupt_truncated_header.shard',
    'corrupt_crc_mismatch.shard',
    'corrupt_truncated_data.shard',
    'corrupt_entry_count_overflow.shard',
    'corrupt_huge_string_table.shard',
  ])('%s', (filename) => {
    it('must throw — never silently succeed', () => {
      const mc = manifest.corrupt.find(c => c.filename === filename)!;
      expect(mc, `${filename} not in manifest`).toBeDefined();

      const buf = loadFixture(filename);
      let threwError = false;

      try {
        const reader = new ShardReader(buf);
        // If the constructor succeeded, try reading all entries.
        // Some corrupt files (e.g. CRC mismatch) only fail on readEntry.
        for (let i = 0; i < reader.entryCount(); i++) {
          reader.readEntry(i);
        }
      } catch (_e) {
        threwError = true;
      }

      expect(threwError, `${filename} (${mc.description}) must throw, not silently succeed`).toBe(true);
    });
  });

  it('rejects empty buffer', () => {
    expect(() => new ShardReader(Buffer.alloc(0))).toThrow();
  });

  it('rejects wrong magic', () => {
    const buf = Buffer.alloc(64, 0);
    buf.write('NOPE', 0, 'ascii');
    expect(() => new ShardReader(buf)).toThrow();
  });

  it('does not crash on random data', () => {
    // 1024 bytes of pseudo-random data — must not cause unhandled exceptions
    const buf = Buffer.alloc(1024);
    // Seed with deterministic pseudo-random values
    let seed = 0xDEADBEEF;
    for (let i = 0; i < buf.length; i++) {
      seed = (seed * 1103515245 + 12345) & 0x7FFFFFFF;
      buf[i] = seed & 0xFF;
    }

    try {
      const reader = new ShardReader(buf);
      for (let i = 0; i < reader.entryCount(); i++) {
        reader.readEntry(i);
      }
    } catch (_e) {
      // Any thrown error is acceptable — the point is no unhandled crash
    }
    // If we reach here without an unhandled exception, the test passes
    expect(true).toBe(true);
  });
});

// ============================================================
// Cross-write test: TS writes a shard, reads back
// ============================================================

describe('safety: cross-write roundtrip', () => {
  it('ShardWriter roundtrip: write and read back entries', () => {
    const writer = new ShardWriter(ROLE_MOSH);
    writer.setAlignment(ALIGN_64);

    const testEntries = [
      { name: 'alpha', data: Buffer.from('hello world') },
      { name: 'beta', data: Buffer.alloc(1024, 0xAB) },
      { name: 'gamma/nested', data: Buffer.from([0, 1, 2, 3, 4, 5]) },
      { name: 'empty', data: Buffer.alloc(0) },
    ];

    for (const entry of testEntries) {
      writer.writeEntry(entry.name, entry.data);
    }

    const buf = writer.toBuffer();
    const reader = new ShardReader(buf);

    expect(reader.entryCount()).toBe(testEntries.length);
    expect(reader.entryNames()).toEqual(testEntries.map(e => e.name));

    for (let i = 0; i < testEntries.length; i++) {
      const expected = testEntries[i];
      const data = reader.readEntry(i);
      expect(data.length, `entry ${expected.name} size`).toBe(expected.data.length);
      expect(sha256hex(data), `entry ${expected.name} SHA256`).toBe(sha256hex(expected.data));
    }
  });

  it('ShardStreamWriter roundtrip: write and read back entries', () => {
    const tmpPath = resolve(tmpdir(), `safety_test_${Date.now()}_${Math.random().toString(36).slice(2)}.shard`);

    try {
      const sw = new ShardStreamWriter(tmpPath, ROLE_MOSH, 100);
      sw.setAlignment(ALIGN_64);
      sw.beginData();

      const testEntries = [
        { name: 'stream_a', data: Buffer.from('stream test data') },
        { name: 'stream_b', data: Buffer.alloc(2048, 0xCD) },
        { name: 'unicode/name', data: Buffer.from('value') },
      ];

      for (const entry of testEntries) {
        sw.writeEntry(entry.name, entry.data);
      }
      sw.finalize();

      const buf = readFileSync(tmpPath);
      const reader = new ShardReader(buf);

      expect(reader.entryCount()).toBe(testEntries.length);
      expect(reader.entryNames()).toEqual(testEntries.map(e => e.name));

      for (let i = 0; i < testEntries.length; i++) {
        const expected = testEntries[i];
        const data = reader.readEntry(i);
        expect(data.length, `entry ${expected.name} size`).toBe(expected.data.length);
        expect(sha256hex(data), `entry ${expected.name} SHA256`).toBe(sha256hex(expected.data));
      }
    } finally {
      // Clean up temp file
      try {
        unlinkSync(tmpPath);
      } catch (_) {
        // ignore cleanup errors
      }
    }
  });

  it('empty entry survives roundtrip', () => {
    const writer = new ShardWriter(ROLE_MOSH);
    writer.writeEntry('empty_test', Buffer.alloc(0));

    const buf = writer.toBuffer();
    const reader = new ShardReader(buf);

    expect(reader.entryCount()).toBe(1);
    const data = reader.readEntry(0);
    expect(data.length).toBe(0);
  });

  it('unicode names survive roundtrip', () => {
    const writer = new ShardWriter(ROLE_MOSH);

    const unicodeEntries = [
      { name: '\u6771\u4EAC\u30BF\u30EF\u30FC', data: Buffer.from('japanese') },      // 東京タワー
      { name: '\uD83D\uDE80\uD83C\uDF1F\u2728', data: Buffer.from('emoji') },          // 🚀🌟✨
      { name: '\u041F\u0440\u0438\u0432\u0435\u0442', data: Buffer.from('cyrillic') },  // Привет
    ];

    for (const entry of unicodeEntries) {
      writer.writeEntry(entry.name, entry.data);
    }

    const buf = writer.toBuffer();
    const reader = new ShardReader(buf);

    expect(reader.entryCount()).toBe(unicodeEntries.length);
    const names = reader.entryNames();
    for (let i = 0; i < unicodeEntries.length; i++) {
      expect(names[i], `unicode name ${i}`).toBe(unicodeEntries[i].name);
      const data = reader.readEntry(i);
      expect(sha256hex(data)).toBe(sha256hex(unicodeEntries[i].data));
    }
  });

  it('large entry (1MB+) roundtrip', () => {
    const writer = new ShardWriter(ROLE_MOSH);

    // 1 MB + 137 bytes (not a round number)
    const size = 1024 * 1024 + 137;
    const largeData = Buffer.alloc(size);
    // Fill with a deterministic pattern
    for (let i = 0; i < size; i++) {
      largeData[i] = (i * 7 + 13) & 0xFF;
    }
    const expectedHash = sha256hex(largeData);
    writer.writeEntry('large_blob', largeData);

    const buf = writer.toBuffer();
    const reader = new ShardReader(buf);

    expect(reader.entryCount()).toBe(1);
    const data = reader.readEntry(0);
    expect(data.length).toBe(size);
    expect(sha256hex(data)).toBe(expectedHash);
  });

  it('many entries (200) roundtrip', () => {
    const writer = new ShardWriter(ROLE_MOSH);

    const count = 200;
    const entries: Array<{ name: string; data: Buffer }> = [];
    for (let i = 0; i < count; i++) {
      const name = `entry_${String(i).padStart(4, '0')}`;
      const data = Buffer.from(`payload_${i}_${'x'.repeat(i % 50)}`);
      entries.push({ name, data });
      writer.writeEntry(name, data);
    }

    const buf = writer.toBuffer();
    const reader = new ShardReader(buf);

    expect(reader.entryCount()).toBe(count);
    const names = reader.entryNames();
    expect(names).toEqual(entries.map(e => e.name));

    for (let i = 0; i < count; i++) {
      const data = reader.readEntry(i);
      expect(data.length, `entry ${entries[i].name} size`).toBe(entries[i].data.length);
      expect(sha256hex(data), `entry ${entries[i].name} SHA256`).toBe(sha256hex(entries[i].data));
    }
  });

  it('detects corruption after write', () => {
    const writer = new ShardWriter(ROLE_MOSH);
    writer.writeEntry('integrity_check', Buffer.from('this data must not be silently corrupted'));

    const buf = writer.toBuffer();

    // Corrupt a byte in the data section (near the end of the buffer)
    const corruptedBuf = Buffer.from(buf);
    const corruptOffset = corruptedBuf.length - 5;
    corruptedBuf[corruptOffset] = corruptedBuf[corruptOffset] ^ 0xFF;

    let threwError = false;
    try {
      const reader = new ShardReader(corruptedBuf);
      for (let i = 0; i < reader.entryCount(); i++) {
        reader.readEntry(i); // checksum verification should catch corruption
      }
    } catch (_e) {
      threwError = true;
    }

    expect(threwError, 'corrupted shard must throw on read').toBe(true);
  });

  it('preserves entry order', () => {
    const writer = new ShardWriter(ROLE_MOSH);

    const orderedNames: string[] = [];
    for (let i = 0; i < 20; i++) {
      // Use non-alphabetical names to verify insertion order, not sorting
      const name = `z${20 - i}_entry_${String.fromCharCode(97 + (i % 26))}`;
      orderedNames.push(name);
      writer.writeEntry(name, Buffer.from(`data_${i}`));
    }

    const buf = writer.toBuffer();
    const reader = new ShardReader(buf);

    expect(reader.entryNames()).toEqual(orderedNames);
  });

  it('lookup works after roundtrip', () => {
    const writer = new ShardWriter(ROLE_MOSH);
    const namedEntries = [
      { name: 'first_entry', data: Buffer.from('aaa') },
      { name: 'second_entry', data: Buffer.from('bbb') },
      { name: 'third_entry', data: Buffer.from('ccc') },
    ];

    for (const entry of namedEntries) {
      writer.writeEntry(entry.name, entry.data);
    }

    const buf = writer.toBuffer();
    const reader = new ShardReader(buf);

    for (let i = 0; i < namedEntries.length; i++) {
      const idx = reader.lookup(namedEntries[i].name);
      expect(idx, `lookup(${namedEntries[i].name})`).toBe(i);
      expect(reader.hasEntry(namedEntries[i].name)).toBe(true);
    }

    // Non-existent name should return -1
    expect(reader.lookup('does_not_exist')).toBe(-1);
    expect(reader.hasEntry('does_not_exist')).toBe(false);
  });

  it('binary data survives roundtrip (all 256 byte values)', () => {
    const writer = new ShardWriter(ROLE_MOSH);
    const allBytes = Buffer.from(Array.from({ length: 256 }, (_, i) => i));
    writer.writeEntry('all_bytes', allBytes);

    const buf = writer.toBuffer();
    const reader = new ShardReader(buf);
    const data = reader.readEntry(0);

    expect(data.length).toBe(256);
    expect(sha256hex(data)).toBe(sha256hex(allBytes));
    for (let i = 0; i < 256; i++) {
      expect(data[i], `byte ${i}`).toBe(i);
    }
  });
});
