//! Cross-language safety tests for the Rust shard implementation.
//!
//! Reads golden safety fixtures generated by the Go `ucodec` package at
//! `../ucodec/testdata/safety/` and verifies that the Rust reader produces
//! identical results, rejects corrupt inputs gracefully (no panics), and
//! roundtrips correctly through the Rust writer.

use serde::Deserialize;
use sha2::{Digest, Sha256};
use shard_format::{ShardV2Reader, ShardV2Writer, ROLE_UNKNOWN};
use std::path::{Path, PathBuf};
use std::sync::Arc;

// ============================================================
// Manifest deserialization structs
// ============================================================

#[derive(Deserialize)]
struct SafetyManifest {
    valid: Vec<ValidFile>,
    corrupt: Vec<CorruptFile>,
}

#[derive(Deserialize)]
struct ValidFile {
    filename: String,
    sha256: String,
    entry_count: usize,
    entries: Vec<ValidEntry>,
}

#[derive(Deserialize)]
struct ValidEntry {
    name: String,
    data_sha256: String,
    size: usize,
}

#[derive(Deserialize)]
struct CorruptFile {
    filename: String,
    expected_error: String,
    description: String,
}

// ============================================================
// Helpers
// ============================================================

fn safety_dir() -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    Path::new(&manifest).join("../ucodec/testdata/safety")
}

fn load_safety_manifest() -> SafetyManifest {
    let path = safety_dir().join("safety_manifest.json");
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("Failed to parse safety manifest: {}", e))
}

fn sha256_hex(data: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(data);
    hex::encode(h.finalize())
}

/// Write entries through ShardV2Writer and return a reader over the result.
/// Uses a temporary file that lives as long as the returned NamedTempFile.
fn write_and_read(
    entries: &[(&str, &[u8])],
) -> (ShardV2Reader, tempfile::NamedTempFile) {
    let mut writer = ShardV2Writer::new(ROLE_UNKNOWN);
    for (name, data) in entries {
        writer.write_entry(name, data);
    }
    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    writer
        .write_to_file(tmp.path())
        .expect("write_to_file failed");
    let reader = ShardV2Reader::from_file(tmp.path()).expect("from_file failed");
    (reader, tmp)
}

// ============================================================
// 1. Valid shard tests
// ============================================================

#[test]
fn test_safety_manifest_exists() {
    let path = safety_dir().join("safety_manifest.json");
    assert!(
        path.exists(),
        "safety_manifest.json not found at {}",
        path.display()
    );
}

#[test]
fn test_valid_files_exist() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let p = dir.join(&vf.filename);
        assert!(
            p.exists(),
            "valid fixture {} not found at {}",
            vf.filename,
            p.display()
        );
    }
}

#[test]
fn test_valid_file_sha256() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let data = std::fs::read(dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("read {}: {}", vf.filename, e));
        let got = sha256_hex(&data);
        assert_eq!(
            got, vf.sha256,
            "whole-file SHA256 mismatch for {}",
            vf.filename
        );
    }
}

#[test]
fn test_valid_from_file_succeeds() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let path = dir.join(&vf.filename);
        let result = ShardV2Reader::from_file(&path);
        assert!(
            result.is_ok(),
            "from_file should succeed for {}: {:?}",
            vf.filename,
            result.err()
        );
    }
}

#[test]
fn test_valid_entry_count() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        assert_eq!(
            reader.entry_count(),
            vf.entry_count,
            "{}: entry_count mismatch",
            vf.filename
        );
    }
}

#[test]
fn test_valid_entry_names() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        let names = reader.entry_names();
        let expected: Vec<&str> = vf.entries.iter().map(|e| e.name.as_str()).collect();
        assert_eq!(
            names, expected,
            "{}: entry names mismatch",
            vf.filename
        );
    }
}

#[test]
fn test_valid_entry_data_sha256() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        for (i, ve) in vf.entries.iter().enumerate() {
            let data = reader.read_entry(i).unwrap_or_else(|e| {
                panic!("{} entry {} ({}): read_entry error: {}", vf.filename, i, ve.name, e)
            });
            assert_eq!(
                data.len(),
                ve.size,
                "{} entry {} ({}): data size mismatch",
                vf.filename,
                i,
                ve.name
            );
            let got = sha256_hex(&data);
            assert_eq!(
                got, ve.data_sha256,
                "{} entry {} ({}): data SHA256 mismatch",
                vf.filename, i, ve.name
            );
        }
    }
}

#[test]
fn test_valid_entry_lookup_by_name() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        for (i, ve) in vf.entries.iter().enumerate() {
            let idx = reader.lookup(&ve.name);
            assert_eq!(
                idx,
                Some(i),
                "{}: lookup({}) returned {:?}, expected Some({})",
                vf.filename,
                ve.name,
                idx,
                i
            );

            // Also verify read_entry_by_name matches read_entry
            let by_name = reader.read_entry_by_name(&ve.name).unwrap_or_else(|e| {
                panic!("{}: read_entry_by_name({}): {}", vf.filename, ve.name, e)
            });
            let by_index = reader.read_entry(i).unwrap_or_else(|e| {
                panic!("{}: read_entry({}): {}", vf.filename, i, e)
            });
            assert_eq!(
                by_name, by_index,
                "{}: read_entry_by_name({}) != read_entry({})",
                vf.filename, ve.name, i
            );
        }
    }
}

// ============================================================
// 1b. Valid shard tests — additional per-entry validation
// ============================================================

#[test]
fn test_valid_entry_data_size_separate() {
    // Verify data sizes match manifest independently from SHA256 checks.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        for (i, ve) in vf.entries.iter().enumerate() {
            let data = reader.read_entry(i).unwrap_or_else(|e| {
                panic!("{} entry {} ({}): read_entry error: {}", vf.filename, i, ve.name, e)
            });
            assert_eq!(
                data.len(),
                ve.size,
                "{} entry {} ({}): size {} != manifest {}",
                vf.filename,
                i,
                ve.name,
                data.len(),
                ve.size
            );
        }
    }
}

#[test]
fn test_valid_lookup_nonexistent() {
    // Verify that lookup("nonexistent") returns None for every valid file.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    let nonexistent_names = [
        "nonexistent",
        "",
        "does_not_exist",
        "tensor_z",
        "../escape",
        "null\0byte",
    ];
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        for name in &nonexistent_names {
            assert_eq!(
                reader.lookup(name),
                None,
                "{}: lookup({:?}) should return None",
                vf.filename,
                name
            );
            assert!(
                !reader.has_entry(name),
                "{}: has_entry({:?}) should be false",
                vf.filename,
                name
            );
        }
    }
}

#[test]
fn test_valid_has_entry() {
    // Verify has_entry returns true for all manifest entries, false for garbage.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        for ve in &vf.entries {
            assert!(
                reader.has_entry(&ve.name),
                "{}: has_entry({}) should be true",
                vf.filename,
                ve.name
            );
        }
        assert!(
            !reader.has_entry("__definitely_not_here__"),
            "{}: has_entry for garbage name should be false",
            vf.filename
        );
    }
}

#[test]
fn test_valid_read_entry_by_name_error_for_missing() {
    // Verify read_entry_by_name returns Err for names not in the shard.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        let result = reader.read_entry_by_name("__does_not_exist__");
        assert!(
            result.is_err(),
            "{}: read_entry_by_name for missing name should return Err",
            vf.filename
        );
    }
}

#[test]
fn test_valid_from_bytes_succeeds() {
    // Verify that from_bytes (in-memory parse) works identically to from_file.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let raw = std::fs::read(dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("read {}: {}", vf.filename, e));
        let reader = ShardV2Reader::from_bytes(raw)
            .unwrap_or_else(|e| panic!("from_bytes {}: {}", vf.filename, e));
        assert_eq!(
            reader.entry_count(),
            vf.entry_count,
            "{}: from_bytes entry_count mismatch",
            vf.filename
        );
        for (i, ve) in vf.entries.iter().enumerate() {
            let data = reader.read_entry(i).unwrap_or_else(|e| {
                panic!("{} from_bytes entry {} ({}): {}", vf.filename, i, ve.name, e)
            });
            assert_eq!(
                sha256_hex(&data),
                ve.data_sha256,
                "{} from_bytes entry {} ({}): SHA256 mismatch",
                vf.filename,
                i,
                ve.name
            );
        }
    }
}

#[test]
fn test_valid_header_fields() {
    // Spot-check header fields on all valid fixtures.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for vf in &manifest.valid {
        let reader = ShardV2Reader::from_file(&dir.join(&vf.filename))
            .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e));
        let hdr = reader.header();
        assert_eq!(
            &hdr.magic, b"SHRD",
            "{}: magic bytes should be SHRD",
            vf.filename
        );
        assert_eq!(
            hdr.version, 0x02,
            "{}: version should be 0x02",
            vf.filename
        );
        assert_eq!(
            hdr.entry_count as usize, vf.entry_count,
            "{}: header entry_count mismatch",
            vf.filename
        );
    }
}

// ============================================================
// 2. Corrupt shard tests
// ============================================================

#[test]
fn test_corrupt_files_exist() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for cf in &manifest.corrupt {
        let p = dir.join(&cf.filename);
        assert!(
            p.exists(),
            "corrupt fixture {} not found at {}",
            cf.filename,
            p.display()
        );
    }
}

#[test]
fn test_corrupt_from_file_returns_err() {
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for cf in &manifest.corrupt {
        let path = dir.join(&cf.filename);
        let result = ShardV2Reader::from_file(&path);

        // For most corrupt files, from_file itself should fail.
        // For corrupt_crc_mismatch, from_file may succeed but read_entry must fail.
        match result {
            Err(e) => {
                println!(
                    "OK: {} correctly rejected at open: {} (expected: {}, desc: {})",
                    cf.filename, e, cf.expected_error, cf.description
                );
            }
            Ok(reader) => {
                // File opened but corruption should surface on read_entry.
                // Try reading all entries; at least one must fail.
                let mut any_read_failed = false;
                for i in 0..reader.entry_count() {
                    if reader.read_entry(i).is_err() {
                        any_read_failed = true;
                        break;
                    }
                }
                assert!(
                    any_read_failed,
                    "{}: from_file succeeded AND all read_entry calls succeeded — \
                     corruption was not detected (expected: {}, desc: {})",
                    cf.filename, cf.expected_error, cf.description
                );
                println!(
                    "OK: {} opened but read_entry correctly failed (expected: {}, desc: {})",
                    cf.filename, cf.expected_error, cf.description
                );
            }
        }
    }
}

#[test]
fn test_corrupt_no_panic() {
    // Ensure that no corrupt file causes a panic. We use catch_unwind
    // as an extra safety net on top of the Err-returning API.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for cf in &manifest.corrupt {
        let path = dir.join(&cf.filename);
        let path_clone = path.clone();
        let result = std::panic::catch_unwind(move || {
            match ShardV2Reader::from_file(&path_clone) {
                Ok(reader) => {
                    for i in 0..reader.entry_count() {
                        let _ = reader.read_entry(i);
                    }
                    let _ = reader.entry_names();
                }
                Err(_) => {}
            }
        });
        assert!(
            result.is_ok(),
            "{}: caused a panic! (desc: {})",
            cf.filename, cf.description
        );
    }
}

#[test]
fn test_corrupt_from_bytes_returns_err() {
    // Verify that from_bytes (in-memory) rejects corrupt data the same as from_file.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for cf in &manifest.corrupt {
        let raw = std::fs::read(dir.join(&cf.filename))
            .unwrap_or_else(|e| panic!("read {}: {}", cf.filename, e));
        let result = ShardV2Reader::from_bytes(raw);
        match result {
            Err(_) => { /* expected */ }
            Ok(reader) => {
                let mut any_read_failed = false;
                for i in 0..reader.entry_count() {
                    if reader.read_entry(i).is_err() {
                        any_read_failed = true;
                        break;
                    }
                }
                assert!(
                    any_read_failed,
                    "{}: from_bytes succeeded AND all reads passed (expected: {}, desc: {})",
                    cf.filename, cf.expected_error, cf.description
                );
            }
        }
    }
}

#[test]
fn test_corrupt_error_messages_contain_info() {
    // Ensure error messages are descriptive, not just empty strings.
    let manifest = load_safety_manifest();
    let dir = safety_dir();
    for cf in &manifest.corrupt {
        let path = dir.join(&cf.filename);
        let result = ShardV2Reader::from_file(&path);
        match result {
            Err(e) => {
                let msg = format!("{}", e);
                assert!(
                    !msg.is_empty(),
                    "{}: error message should not be empty",
                    cf.filename
                );
                assert!(
                    msg.len() > 5,
                    "{}: error message '{}' is too short to be informative",
                    cf.filename,
                    msg
                );
            }
            Ok(reader) => {
                // For files that open successfully, the error comes from read_entry.
                for i in 0..reader.entry_count() {
                    if let Err(e) = reader.read_entry(i) {
                        let msg = format!("{}", e);
                        assert!(
                            !msg.is_empty(),
                            "{}: read_entry error message should not be empty",
                            cf.filename
                        );
                        assert!(
                            msg.len() > 5,
                            "{}: read_entry error message '{}' is too short",
                            cf.filename,
                            msg
                        );
                        break;
                    }
                }
            }
        }
    }
}

#[test]
fn test_corrupt_empty_file() {
    // A zero-byte file must be rejected.
    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    std::fs::write(tmp.path(), b"").expect("write empty file");
    let result = ShardV2Reader::from_file(tmp.path());
    assert!(
        result.is_err(),
        "empty file should be rejected"
    );
}

#[test]
fn test_corrupt_short_magic() {
    // A file with only 3 bytes (incomplete magic) must be rejected.
    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    std::fs::write(tmp.path(), b"SHR").expect("write short magic");
    let result = ShardV2Reader::from_file(tmp.path());
    assert!(
        result.is_err(),
        "file with incomplete magic should be rejected"
    );
}

#[test]
fn test_corrupt_wrong_magic() {
    // A 64-byte file with wrong magic must be rejected.
    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    let mut data = vec![0u8; 64];
    data[0..4].copy_from_slice(b"NOPE");
    std::fs::write(tmp.path(), &data).expect("write wrong magic");
    let result = ShardV2Reader::from_file(tmp.path());
    assert!(
        result.is_err(),
        "file with wrong magic should be rejected"
    );
}

#[test]
fn test_corrupt_all_zeros() {
    // A file of all zeros must be rejected (magic won't match).
    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    std::fs::write(tmp.path(), &vec![0u8; 128]).expect("write zeros");
    let result = ShardV2Reader::from_file(tmp.path());
    assert!(
        result.is_err(),
        "all-zeros file should be rejected"
    );
}

#[test]
fn test_corrupt_random_bytes() {
    // Random-looking bytes should be rejected, not cause panics.
    let data: Vec<u8> = (0..1024).map(|i| ((i * 7 + 13) % 256) as u8).collect();
    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    std::fs::write(tmp.path(), &data).expect("write random bytes");
    let result = std::panic::catch_unwind(|| {
        let _ = ShardV2Reader::from_file(tmp.path());
    });
    assert!(
        result.is_ok(),
        "random bytes should not cause a panic"
    );
}

// ============================================================
// 3. Cross-write test (Rust writes, Rust reads back)
// ============================================================

#[test]
fn test_cross_write_roundtrip() {
    let entries: Vec<(&str, Vec<u8>)> = vec![
        ("alpha", [0xDEu8, 0xAD, 0xBE, 0xEF].iter().copied().cycle().take(256).collect()),
        ("beta/weights", (0..256).map(|i| i as u8).collect()),
        ("gamma", vec![0u8; 1024]),
    ];

    // Write using ShardV2Writer
    let mut writer = ShardV2Writer::new(ROLE_UNKNOWN);
    for (name, data) in &entries {
        writer.write_entry(name, data);
    }

    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    writer
        .write_to_file(tmp.path())
        .expect("write_to_file failed");

    // Read back
    let reader =
        ShardV2Reader::from_file(tmp.path()).expect("from_file on roundtrip shard failed");

    assert_eq!(reader.entry_count(), entries.len(), "entry count mismatch");

    for (i, (name, data)) in entries.iter().enumerate() {
        assert_eq!(
            reader.entry_name(i),
            *name,
            "entry {} name mismatch",
            i
        );

        let read_data = reader
            .read_entry(i)
            .unwrap_or_else(|e| panic!("read_entry({}) failed: {}", i, e));
        assert_eq!(
            read_data.len(),
            data.len(),
            "entry {} ({}) size mismatch",
            i,
            name
        );

        let expected_hash = sha256_hex(data);
        let got_hash = sha256_hex(&read_data);
        assert_eq!(
            got_hash, expected_hash,
            "entry {} ({}) SHA256 mismatch",
            i, name
        );
    }
}

#[test]
fn test_cross_write_by_name_lookup() {
    let mut writer = ShardV2Writer::new(ROLE_UNKNOWN);
    writer.write_entry("foo", b"hello");
    writer.write_entry("bar/baz", b"world");
    writer.write_entry("qux", b"!");

    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    writer
        .write_to_file(tmp.path())
        .expect("write_to_file failed");

    let reader = ShardV2Reader::from_file(tmp.path()).expect("from_file failed");

    assert_eq!(reader.lookup("foo"), Some(0));
    assert_eq!(reader.lookup("bar/baz"), Some(1));
    assert_eq!(reader.lookup("qux"), Some(2));
    assert_eq!(reader.lookup("nonexistent"), None);

    let data = reader.read_entry_by_name("bar/baz").expect("read bar/baz");
    assert_eq!(data, b"world");
}

#[test]
fn test_cross_write_empty_entry() {
    // Write an entry with zero-length data, read back and verify.
    let (reader, _tmp) = write_and_read(&[("empty_entry", &[])]);

    assert_eq!(reader.entry_count(), 1, "should have 1 entry");
    assert_eq!(reader.entry_name(0), "empty_entry");

    let data = reader.read_entry(0).expect("read empty entry");
    assert_eq!(data.len(), 0, "empty entry should have 0 bytes");
    assert_eq!(
        sha256_hex(&data),
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "SHA256 of empty data should match known hash"
    );
}

#[test]
fn test_cross_write_unicode_names() {
    // Write entries with Unicode names (emoji, CJK, Arabic, Cyrillic), read back.
    let entries: Vec<(&str, &[u8])> = vec![
        ("\u{65e5}\u{672c}\u{8a9e}", b"nihongo" as &[u8]),       // Japanese
        ("emoji_\u{1f600}_face", b"grinning"),                    // emoji
        ("\u{0627}\u{0644}\u{0639}\u{0631}\u{0628}\u{064a}\u{0629}", b"arabic"), // Arabic
        ("\u{0410}\u{0411}\u{0412}\u{0413}", b"cyrillic"),        // Cyrillic
        ("mixed/\u{4e2d}\u{6587}/path", b"chinese_path"),         // CJK in path
    ];

    let (reader, _tmp) = write_and_read(&entries);

    assert_eq!(reader.entry_count(), entries.len(), "entry count mismatch");

    for (i, (name, data)) in entries.iter().enumerate() {
        assert_eq!(
            reader.entry_name(i), *name,
            "entry {} unicode name mismatch",
            i
        );
        let read_data = reader.read_entry(i).unwrap_or_else(|e| {
            panic!("entry {} ({}): read error: {}", i, name, e)
        });
        assert_eq!(
            read_data, *data,
            "entry {} ({}) data mismatch",
            i, name
        );
        // Verify lookup by unicode name works
        assert_eq!(
            reader.lookup(name), Some(i),
            "lookup({}) should return Some({})",
            name, i
        );
    }
}

#[test]
fn test_cross_write_large_entry() {
    // Write a 1 MB+ entry, verify SHA256 integrity on round-trip.
    let size = 1_048_576 + 1337; // 1 MB + 1337 bytes
    let large_data: Vec<u8> = (0..size).map(|i| (i % 251) as u8).collect();
    let expected_sha = sha256_hex(&large_data);

    let mut writer = ShardV2Writer::new(ROLE_UNKNOWN);
    writer.write_entry("large_tensor", &large_data);

    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    writer
        .write_to_file(tmp.path())
        .expect("write_to_file failed");

    let reader = ShardV2Reader::from_file(tmp.path()).expect("from_file failed");
    assert_eq!(reader.entry_count(), 1);
    assert_eq!(reader.entry_name(0), "large_tensor");

    let read_data = reader.read_entry(0).expect("read large entry");
    assert_eq!(read_data.len(), size, "large entry size mismatch");
    assert_eq!(
        sha256_hex(&read_data),
        expected_sha,
        "large entry SHA256 mismatch"
    );
}

#[test]
fn test_cross_write_many_entries() {
    // Write 200 entries, verify all round-trip correctly.
    let count = 200;
    let entries: Vec<(String, Vec<u8>)> = (0..count)
        .map(|i| {
            let name = format!("layer_{:04}/weights", i);
            // Each entry has unique data seeded by its index.
            let data: Vec<u8> = (0..128).map(|j| ((i * 7 + j * 13) % 256) as u8).collect();
            (name, data)
        })
        .collect();

    let mut writer = ShardV2Writer::new(ROLE_UNKNOWN);
    for (name, data) in &entries {
        writer.write_entry(name, data);
    }

    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    writer
        .write_to_file(tmp.path())
        .expect("write_to_file failed");

    let reader = ShardV2Reader::from_file(tmp.path()).expect("from_file failed");
    assert_eq!(reader.entry_count(), count, "entry count mismatch for many entries");

    for (i, (name, data)) in entries.iter().enumerate() {
        assert_eq!(
            reader.entry_name(i), name.as_str(),
            "entry {} name mismatch",
            i
        );
        let read_data = reader.read_entry(i).unwrap_or_else(|e| {
            panic!("entry {} ({}): read error: {}", i, name, e)
        });
        assert_eq!(
            sha256_hex(&read_data),
            sha256_hex(data),
            "entry {} ({}) SHA256 mismatch",
            i,
            name
        );
    }

    // Verify name lookups work for a sampling of entries.
    for i in [0, 50, 99, 150, 199] {
        let name = &entries[i].0;
        assert_eq!(
            reader.lookup(name.as_str()),
            Some(i),
            "lookup({}) failed",
            name
        );
    }
}

#[test]
fn test_cross_write_binary_data_all_byte_values() {
    // Write all 256 byte values and verify exact content on read-back.
    let all_bytes: Vec<u8> = (0..=255u8).collect();
    let expected_sha = sha256_hex(&all_bytes);

    let (reader, _tmp) = write_and_read(&[("all_bytes", &all_bytes)]);

    let data = reader.read_entry(0).expect("read all_bytes");
    assert_eq!(data.len(), 256);
    assert_eq!(sha256_hex(&data), expected_sha);
    for i in 0..256 {
        assert_eq!(
            data[i], i as u8,
            "byte {} mismatch: got {}, expected {}",
            i, data[i], i
        );
    }
}

#[test]
fn test_cross_write_crc_integrity() {
    // Write a shard, read it back to confirm CRC passes, then corrupt a data
    // byte in the file and verify that the reader detects the corruption.
    let original_data = b"integrity check payload with enough bytes to matter";

    let mut writer = ShardV2Writer::new(ROLE_UNKNOWN);
    writer.write_entry("crc_test", original_data);

    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    writer
        .write_to_file(tmp.path())
        .expect("write_to_file failed");

    // First, verify the shard reads cleanly.
    {
        let reader = ShardV2Reader::from_file(tmp.path()).expect("from_file failed");
        let data = reader.read_entry(0).expect("initial read should succeed");
        assert_eq!(data, original_data, "initial data mismatch");
    }

    // Now corrupt a byte in the data section. The data section is after the
    // header + index + string table, so we corrupt near the end of the file
    // (but before the last byte to avoid total_file_size mismatch).
    {
        let mut file_bytes = std::fs::read(tmp.path()).expect("read shard file");
        let corrupt_pos = file_bytes.len() - 10;
        file_bytes[corrupt_pos] ^= 0xFF; // flip all bits of one byte
        std::fs::write(tmp.path(), &file_bytes).expect("write corrupted shard");
    }

    // Read the corrupted file — it should either fail to open or fail on read_entry.
    let result = ShardV2Reader::from_file(tmp.path());
    match result {
        Err(_) => {
            // Corruption detected at open time — acceptable.
        }
        Ok(reader) => {
            let read_result = reader.read_entry(0);
            assert!(
                read_result.is_err(),
                "reading corrupted entry should fail (CRC mismatch)"
            );
        }
    }
}

#[test]
fn test_cross_write_single_byte_entry() {
    // Edge case: a single-byte entry.
    let (reader, _tmp) = write_and_read(&[("one", &[0x42])]);
    let data = reader.read_entry(0).expect("read single byte");
    assert_eq!(data, &[0x42]);
}

#[test]
fn test_cross_write_duplicate_like_names() {
    // Entries with similar but distinct names should not collide.
    let entries: Vec<(&str, &[u8])> = vec![
        ("a", b"first" as &[u8]),
        ("aa", b"second"),
        ("a/a", b"third"),
        ("a/b", b"fourth"),
    ];
    let (reader, _tmp) = write_and_read(&entries);

    assert_eq!(reader.entry_count(), 4);
    for (i, (name, data)) in entries.iter().enumerate() {
        assert_eq!(reader.entry_name(i), *name);
        let read = reader.read_entry(i).expect("read entry");
        assert_eq!(read, *data, "entry {} ({}) data mismatch", i, name);
        assert_eq!(reader.lookup(name), Some(i));
    }
}

#[test]
fn test_cross_write_to_bytes_matches_to_file() {
    // Verify that to_bytes() produces identical output to write_to_file().
    let mut writer = ShardV2Writer::new(ROLE_UNKNOWN);
    writer.write_entry("x", b"data_x");
    writer.write_entry("y", b"data_y");

    let in_memory = writer.to_bytes();

    let tmp = tempfile::NamedTempFile::new().expect("create tempfile");
    writer
        .write_to_file(tmp.path())
        .expect("write_to_file failed");
    let on_disk = std::fs::read(tmp.path()).expect("read file");

    assert_eq!(in_memory, on_disk, "to_bytes() and write_to_file() should produce identical output");

    // Both should be readable.
    let reader = ShardV2Reader::from_bytes(in_memory).expect("from_bytes");
    assert_eq!(reader.entry_count(), 2);
    assert_eq!(
        reader.read_entry(0).expect("read x"),
        b"data_x"
    );
    assert_eq!(
        reader.read_entry(1).expect("read y"),
        b"data_y"
    );
}

// ============================================================
// 4. Concurrent read tests
// ============================================================

#[test]
fn test_concurrent_reads() {
    let dir = safety_dir();
    let path = dir.join("valid_basic.shard");
    let reader = Arc::new(
        ShardV2Reader::from_file(&path).expect("open valid_basic.shard for concurrent test"),
    );

    let num_threads = 10;
    let mut handles = Vec::with_capacity(num_threads);

    for thread_id in 0..num_threads {
        let reader_clone = Arc::clone(&reader);
        handles.push(std::thread::spawn(move || {
            // Each thread reads all entries and verifies SHA256 against the
            // manifest values (hardcoded from valid_basic.shard).
            let expected_hashes = [
                ("tensor_a", "477e0dc549fdaf0f7a6e00a1c693454096d0aecbc6610ec820b377e70e712b17"),
                ("tensor_b", "347e635d9369f762d476eee696313d7073a0536d89f2dfe1c0c5712b1a719ed1"),
                ("tensor_c", "2034f7bb7a3a79f0b9651811aafd266b605c6d4c817c3fc4ce94e367dff216d8"),
            ];

            assert_eq!(
                reader_clone.entry_count(),
                expected_hashes.len(),
                "thread {}: entry count mismatch",
                thread_id
            );

            for (i, (expected_name, expected_sha)) in expected_hashes.iter().enumerate() {
                let name = reader_clone.entry_name(i);
                assert_eq!(
                    name, *expected_name,
                    "thread {} entry {}: name mismatch",
                    thread_id, i
                );

                let data = reader_clone
                    .read_entry(i)
                    .unwrap_or_else(|e| {
                        panic!("thread {} entry {}: read_entry error: {}", thread_id, i, e)
                    });

                let got = sha256_hex(&data);
                assert_eq!(
                    got, *expected_sha,
                    "thread {} entry {} ({}): SHA256 mismatch",
                    thread_id, i, expected_name
                );
            }
        }));
    }

    for (i, handle) in handles.into_iter().enumerate() {
        handle
            .join()
            .unwrap_or_else(|e| panic!("thread {} panicked: {:?}", i, e));
    }
}

#[test]
fn test_concurrent_reads_all_valid() {
    // Test concurrent reads on ALL valid fixtures, not just valid_basic.
    let manifest = load_safety_manifest();
    let dir = safety_dir();

    for vf in &manifest.valid {
        let path = dir.join(&vf.filename);
        let reader = Arc::new(
            ShardV2Reader::from_file(&path)
                .unwrap_or_else(|e| panic!("open {}: {}", vf.filename, e)),
        );

        // Build expected SHA256 map from manifest.
        let expected: Vec<(String, String)> = vf
            .entries
            .iter()
            .map(|e| (e.name.clone(), e.data_sha256.clone()))
            .collect();
        let expected = Arc::new(expected);

        let num_threads = 4;
        let mut handles = Vec::with_capacity(num_threads);

        for thread_id in 0..num_threads {
            let reader_c = Arc::clone(&reader);
            let expected_c = Arc::clone(&expected);
            let filename = vf.filename.clone();

            handles.push(std::thread::spawn(move || {
                assert_eq!(
                    reader_c.entry_count(),
                    expected_c.len(),
                    "thread {} {}: entry count mismatch",
                    thread_id,
                    filename
                );

                for (i, (expected_name, expected_sha)) in expected_c.iter().enumerate() {
                    let name = reader_c.entry_name(i);
                    assert_eq!(
                        name, expected_name.as_str(),
                        "thread {} {} entry {}: name mismatch",
                        thread_id, filename, i
                    );

                    let data = reader_c.read_entry(i).unwrap_or_else(|e| {
                        panic!(
                            "thread {} {} entry {} ({}): {}",
                            thread_id, filename, i, expected_name, e
                        )
                    });

                    let got = sha256_hex(&data);
                    assert_eq!(
                        got,
                        expected_sha.as_str(),
                        "thread {} {} entry {} ({}): SHA256 mismatch",
                        thread_id,
                        filename,
                        i,
                        expected_name
                    );
                }
            }));
        }

        for (i, handle) in handles.into_iter().enumerate() {
            handle.join().unwrap_or_else(|e| {
                panic!(
                    "thread {} panicked on {}: {:?}",
                    i, vf.filename, e
                )
            });
        }
    }
}

#[test]
fn test_concurrent_reads_stress() {
    // 50 threads, each reading all entries 5 times — stress test for data races.
    let dir = safety_dir();
    let path = dir.join("valid_basic.shard");
    let reader = Arc::new(
        ShardV2Reader::from_file(&path).expect("open valid_basic.shard for stress test"),
    );

    let manifest = load_safety_manifest();
    let vf = &manifest.valid[0]; // valid_basic.shard
    let expected: Vec<(String, String, usize)> = vf
        .entries
        .iter()
        .map(|e| (e.name.clone(), e.data_sha256.clone(), e.size))
        .collect();
    let expected = Arc::new(expected);

    let num_threads = 50;
    let iterations_per_thread = 5;
    let mut handles = Vec::with_capacity(num_threads);

    for thread_id in 0..num_threads {
        let reader_c = Arc::clone(&reader);
        let expected_c = Arc::clone(&expected);

        handles.push(std::thread::spawn(move || {
            for iter in 0..iterations_per_thread {
                for (i, (expected_name, expected_sha, expected_size)) in
                    expected_c.iter().enumerate()
                {
                    let name = reader_c.entry_name(i);
                    assert_eq!(
                        name, expected_name.as_str(),
                        "thread {} iter {} entry {}: name mismatch",
                        thread_id, iter, i
                    );

                    let data = reader_c.read_entry(i).unwrap_or_else(|e| {
                        panic!(
                            "thread {} iter {} entry {} ({}): {}",
                            thread_id, iter, i, expected_name, e
                        )
                    });

                    assert_eq!(
                        data.len(),
                        *expected_size,
                        "thread {} iter {} entry {} ({}): size mismatch",
                        thread_id,
                        iter,
                        i,
                        expected_name
                    );

                    let got = sha256_hex(&data);
                    assert_eq!(
                        got,
                        expected_sha.as_str(),
                        "thread {} iter {} entry {} ({}): SHA256 mismatch",
                        thread_id,
                        iter,
                        i,
                        expected_name
                    );
                }
            }
        }));
    }

    for (i, handle) in handles.into_iter().enumerate() {
        handle
            .join()
            .unwrap_or_else(|e| panic!("stress thread {} panicked: {:?}", i, e));
    }
}

#[test]
fn test_concurrent_reads_with_lookups() {
    // Concurrent threads performing interleaved read_entry and lookup operations.
    let dir = safety_dir();
    let path = dir.join("valid_basic.shard");
    let reader = Arc::new(
        ShardV2Reader::from_file(&path).expect("open valid_basic.shard for lookup concurrency"),
    );

    let num_threads = 20;
    let mut handles = Vec::with_capacity(num_threads);

    for thread_id in 0..num_threads {
        let reader_c = Arc::clone(&reader);
        handles.push(std::thread::spawn(move || {
            // Alternate between lookup and read_entry_by_name.
            let names = ["tensor_a", "tensor_b", "tensor_c"];
            for round in 0..3 {
                for (i, name) in names.iter().enumerate() {
                    let idx = reader_c.lookup(name);
                    assert_eq!(
                        idx,
                        Some(i),
                        "thread {} round {} lookup({}): got {:?}",
                        thread_id,
                        round,
                        name,
                        idx
                    );
                    let by_name = reader_c
                        .read_entry_by_name(name)
                        .unwrap_or_else(|e| {
                            panic!(
                                "thread {} round {} read_entry_by_name({}): {}",
                                thread_id, round, name, e
                            )
                        });
                    let by_index = reader_c.read_entry(i).unwrap_or_else(|e| {
                        panic!(
                            "thread {} round {} read_entry({}): {}",
                            thread_id, round, i, e
                        )
                    });
                    assert_eq!(
                        by_name, by_index,
                        "thread {} round {}: by_name({}) != by_index({})",
                        thread_id, round, name, i
                    );
                }
                // Also verify nonexistent lookup doesn't crash under concurrency.
                assert_eq!(
                    reader_c.lookup("nonexistent"),
                    None,
                    "thread {} round {}: nonexistent lookup should be None",
                    thread_id,
                    round
                );
            }
        }));
    }

    for (i, handle) in handles.into_iter().enumerate() {
        handle
            .join()
            .unwrap_or_else(|e| panic!("lookup thread {} panicked: {:?}", i, e));
    }
}

// ============================================================
// 5. Edge case tests
// ============================================================

#[test]
fn test_cross_write_entry_names_with_special_chars() {
    // Names with dots, dashes, underscores, and deep nesting.
    let entries: Vec<(&str, &[u8])> = vec![
        ("layer.0.weight", b"w0" as &[u8]),
        ("layer-1-bias", b"b1"),
        ("a/b/c/d/e/f", b"deep"),
        ("name_with_underscores", b"u"),
        ("123numeric", b"n"),
    ];
    let (reader, _tmp) = write_and_read(&entries);

    assert_eq!(reader.entry_count(), entries.len());
    for (i, (name, data)) in entries.iter().enumerate() {
        assert_eq!(reader.entry_name(i), *name);
        assert_eq!(reader.lookup(name), Some(i));
        let read = reader.read_entry(i).expect("read entry");
        assert_eq!(read, *data);
    }
}

#[test]
fn test_cross_write_exact_power_of_two_sizes() {
    // Test entries at exact power-of-two boundaries (alignment edge cases).
    for &size in &[1usize, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 4096] {
        let data: Vec<u8> = (0..size).map(|i| (i % 256) as u8).collect();
        let name = format!("pow2_{}", size);

        let (reader, _tmp) = write_and_read(&[(&name, &data)]);
        let read = reader.read_entry(0).unwrap_or_else(|e| {
            panic!("size {}: read error: {}", size, e)
        });
        assert_eq!(
            read.len(),
            size,
            "size {}: length mismatch",
            size
        );
        assert_eq!(
            sha256_hex(&read),
            sha256_hex(&data),
            "size {}: SHA256 mismatch",
            size
        );
    }
}

#[test]
fn test_cross_write_preserves_entry_order() {
    // Verify that entry order is preserved exactly as written.
    let names: Vec<String> = (0..20)
        .map(|i| format!("entry_{:02}", 19 - i)) // reverse order
        .collect();
    let entries: Vec<(&str, &[u8])> = names
        .iter()
        .map(|n| (n.as_str(), b"data" as &[u8]))
        .collect();

    let (reader, _tmp) = write_and_read(&entries);

    let read_names = reader.entry_names();
    let expected_names: Vec<&str> = names.iter().map(|s| s.as_str()).collect();
    assert_eq!(
        read_names, expected_names,
        "entry order must be preserved"
    );
}

#[test]
fn test_cross_write_list_prefix() {
    // Verify list_prefix returns correct entries.
    let entries: Vec<(&str, &[u8])> = vec![
        ("model/layer0/weight", b"w0" as &[u8]),
        ("model/layer0/bias", b"b0"),
        ("model/layer1/weight", b"w1"),
        ("config", b"cfg"),
    ];
    let (reader, _tmp) = write_and_read(&entries);

    let model_entries = reader.list_prefix("model");
    assert_eq!(model_entries.len(), 3, "model/ prefix should match 3 entries");
    for name in &model_entries {
        assert!(
            name.starts_with("model/"),
            "list_prefix result '{}' should start with 'model/'",
            name
        );
    }

    let layer0_entries = reader.list_prefix("model/layer0");
    assert_eq!(layer0_entries.len(), 2, "model/layer0/ prefix should match 2 entries");

    let config_entries = reader.list_prefix("config");
    assert_eq!(config_entries.len(), 1, "config prefix should match 1 entry");

    let none_entries = reader.list_prefix("nonexistent");
    assert!(none_entries.is_empty(), "nonexistent prefix should match 0 entries");
}

#[test]
fn test_cross_write_list_children() {
    // Verify list_children returns immediate children only.
    let entries: Vec<(&str, &[u8])> = vec![
        ("a/b/c", b"abc" as &[u8]),
        ("a/b/d", b"abd"),
        ("a/e", b"ae"),
        ("f", b"f"),
    ];
    let (reader, _tmp) = write_and_read(&entries);

    let root_children = reader.list_children("");
    // Should have: "a/", "f"
    assert!(
        root_children.contains(&"a/".to_string()),
        "root children should contain 'a/'"
    );
    assert!(
        root_children.contains(&"f".to_string()),
        "root children should contain 'f'"
    );
    assert_eq!(root_children.len(), 2, "root should have 2 children");

    let a_children = reader.list_children("a/");
    // Should have: "a/b/", "a/e"
    assert!(
        a_children.contains(&"a/b/".to_string()),
        "a/ children should contain 'a/b/'"
    );
    assert!(
        a_children.contains(&"a/e".to_string()),
        "a/ children should contain 'a/e'"
    );
    assert_eq!(a_children.len(), 2, "a/ should have 2 children");
}
